alias gccw="gcc -Wall -Wextra -Werror "
alias norm="norminette -R CheckForbiddenSourceHeader"
alias ~="cd ~"
alias f="open ."
alias a="./a.out"
alias arm="a && rm a.out"
alias gcca="gcc -Wall -Wextra -Werror * && a"
alias gcarm="gcc -Wall -Wextra -Werror * && ./a.out && rm 'a.out'"
alias gl="git log"
alias gcm="git commit -m"
alias gpo="git push origin master"
alias gp="git push"
alias ga="git add"
alias gcl="git clone"
alias gs="git status"

